# Generated by Django 4.2.5 on 2024-07-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hologram',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hologram',
            name='ausgestorben_seit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
