# Generated by Django 4.2.5 on 2024-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_remove_hologram_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hologram',
            name='superkraft',
            field=models.CharField(max_length=100),
        ),
    ]
